[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    'solidity-bytes-utils/=lib/solidity-bytes-utils',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
   "@uniswap/v2-core/=lib/v2-core/", 
   "@uniswap/v2-periphery/=lib/v2-periphery/",
   "@openzeppelin/=lib/openzeppelin-contracts/"
]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
